### ISSUE TITLE
[Refactoring] Firebase에서 memoCreatedAt 필드가 String이 아니어야 할 것 같습니다.

### ISSUE THREAD

**Issue by iAmSomething** [APP-iOS3rd/PJ3T2_Mymory#106]
# 리팩토링
앞으로 메모 개수가 늘어나면, 특정 time 이후에 작성된 메모들을 가져와야 하는 로직이 필요할 것으로 사료됩니다.
그래서 CreatedAt 시간 값을 Comparable 한 값으로 관리해야 할 것 같아요
## 현행
memoCreatedAt: String

## 요구사항
- memoCreatedAt 값을 TimeInterval 값으로 변경하기(Double) 입니다.

## Todo
- [ ] memoCreatedAt 값을 TimeInterval 값으로 변경하기(Double) 입니다.
- [ ] 변경했을 때 오류 발생하지 않는지 체크해보기


**Comment by jeonguk29** [comment]
MemoService.swift에서 fetchMemoFromDocument메서드를 확인해 보니 이미 date: memoCreatedAt로 저장 되는 것을 확인했습니다!!
