### ISSUE TITLE
[Bug] 로그인이 실패했을 때의 Action이 없습니다.

### ISSUE THREAD

**Issue by iAmSomething** [APP-iOS3rd/PJ3T2_Mymory#111]
## **버그를 작성해 주세요**
로그인 하는 순간 일부러 틀리게 작성해 봤는데, 로그인 실패 로그가 나왔음에도 불구하고 로그인이 된 것 처럼 진행되었습니다.

## **발생 상황**

발생하는 순서:
1. 로그인 뷰로 이동
2. 틀린 계정 정보 작성
3. 로그인 버튼 클릭
4. 틀린 계정 정보임에도 뷰가 사라지고, 메모 작성 페이지에 접근이 가능해짐

## **원래는 이렇게 되어야 합니다**
제안은 다음과 같습니다
- Alert를 통해 틀린 계정임을 알려주는 방법
- id와 pw를 초기화 한 다음 텍스트필드 하단에 "존재하지 않는 회원입니다." 와 같은 붉은 메시지 추가해주기
등이 있습니다.
## **Screenshots**

https://github.com/APP-iOS3rd/PJ3T2_Mymory/assets/38745420/677fa992-205d-40d4-93e4-8246708123af

가능하다면, 발생하는 스크린샷을 추가해주세요

**Comment by Ahario** [comment]
다른앱들을 찾아보니까 두번째 방법이 보기 깔끔하고 고급진것같습니다. 일단 임시로 alert형식으로 만들고, 추후에는 두번째 방식으로 만들면될것같아요.
