### ISSUE TITLE
[Bug] 마이페이지에서 로그아웃 후 재 로그인시 무한 로딩에 빠집니다.

### ISSUE THREAD

**Issue by Seobe95** [APP-iOS3rd/PJ3T2_Mymory#116]
## **버그를 작성해 주세요**
마이페이지에서 로그아웃 후 재 로그인 시 무한 로딩에 걸리게 됩니다.
- 정상적인 로딩화면과 다르게 작동 (정상 - 탭바까지 로딩뷰로 덮임, 비정상 - 탭바를 제외한 메인 화면이 로딩뷰로 덮임)

## **발생 상황**
1. 로그인 상태에서 로그아웃을 한다
2. 다시 로그인을 한다
3. 무한로딩에 걸린다.
4. 탭 바를 이용하여 다른 화면으로 이동할 수 있지만, 마이페이지로 돌아오더라도 로딩이 끝나지 않는다.

## **원래는 이렇게 되어야 합니다**
정상적인 작동으로는, 다시 로그인을 하더라도 로딩 후 로딩화면이 없어진 마이페이지가 나타나야 합니다.

## **Screenshots**

https://github.com/APP-iOS3rd/PJ3T2_Mymory/assets/79817557/fb4b67c3-43bc-49da-b391-20d3197e57fa

**Comment by Ahario** [comment]
이거 이슈는 제가 close할게요. 로그인 문제인지 마이페이지 문제인지는 모르겠는데 현재 특정 동작후 마이페이지 이동시 무한로딩에 빠지는 현상이 발견돼서요
