### ISSUE TITLE
로그인 뷰 디테일한 부분 제안

### ISSUE THREAD

**Issue by iAmSomething** [APP-iOS3rd/PJ3T2_Mymory#134]
# 개선사항 제안
- [ ] 이메일 입력 필드 형식이 email이라면 좋겠습니다(아이폰에서 등록된 keychain으로 대응할 . 수있게 )
- [x] 회원가입으로 이동하는 navigation이 안되고 있어요! navigationStack으로 로그인뷰를 한번 싹 감싸주세요
- [x] 잘못된 로그인 시도 시 그냥 dismiss되는 부분이 맞는지 모르겠어요

**Comment by Seobe95** [comment]
#116 번 이슈와 함께 제가 작업해보겠습니당

**Comment by Ahario** [comment]
명섭님 잘못된 로그인 시 alert뜨는 부분은 제가 구현했습니다. 위에 두개만하시면 될것같습니다.
