### ISSUE TITLE
[Bug] 다크모드 사용시 textField의 입력값들이 보이지않거나 이상하게보이는 현상이 있습니다

### ISSUE THREAD

**Issue by Ahario** [APP-iOS3rd/PJ3T2_Mymory#140]
![IMG_3664](https://github.com/APP-iOS3rd/PJ3T2_Mymory/assets/81345604/3d1eed34-68d4-4250-85c4-d7e1a69ef56d)

**Comment by xohxe** [comment]
![IMG_F514ADF2ACAB-1](https://github.com/APP-iOS3rd/PJ3T2_Mymory/assets/75136643/eec1c0c2-2248-46f7-95cf-cc5da7c38b03)

해당 부분 수정 했습니다.
