### ISSUE TITLE
[Bug] 기존 유저, 애플 로그인 시 Crash

### ISSUE THREAD

**Issue by xohxe** [APP-iOS3rd/PJ3T2_Mymory#171]
## **버그를 작성해 주세요**
버그를 자세하게 설명해주세요

## **발생 상황**
TestFlight에서 애플 로그인 시, 앱 Crash가 발생합니다.
기존 애플 로그인 유저의 경우 발생합니다.

## **원래는 이렇게 되어야 합니다**
설명을 작성해 주세요

## **Screenshots** 

https://github.com/APP-iOS3rd/PJ3T2_Mymory/assets/75136643/566ce705-e397-41b9-a7a3-33c5858a1acd

**Comment by iAmSomething** [comment]
요거 앱 충돌됨 공유로 해주실 수 있을까여?

**Comment by Ahario** [comment]
확인해보니까 작성하기에서 어떠한 방식으로든 로그인을 시도할경우 튕기는것같습니다

**Comment by Ahario** [comment]
뷰를 넘어갈때 Environment Object를 넘겨받지 못해서 생긴 에러였습니다.
