### ISSUE TITLE
[Refactoring] 메인 카드뷰의 스크롤 단위

### ISSUE THREAD

**Issue by xohxe** [APP-iOS3rd/PJ3T2_Mymory#208]
# 리팩토링

가로로 스크롤링 되는 카드뷰를 스트롤당 한개식 넘어가게 구현해보자. 

https://github.com/APP-iOS3rd/PJ3T2_Mymory/assets/75136643/154b6149-aeb4-488b-9e8a-28354931c166

## 요구사항
- 위 영상 처럼 스크롤시 하나씩 넘어가게 변경하기
- tabView page모드로 바꿔야할듯

## Todo
- [ ] ScrollView 대신 tabView로 변경하기
- [ ] 기능이 정상적으로 작동하는지 확인

**Comment by RapidSloth** [comment]
.scrollTargetBehavior 사용하면 해결가능합니다!

**Comment by xohxe** [comment]
오 더 간단한 방법으로 가능했군요! 덕분에 잘 적용했습니다!
